# Generated by Django 4.1.2 on 2022-12-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youpayclient', '0002_youpayclienttransactiondata_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youpayclienttransactiondata',
            name='available_amount',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Available amount for the card', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='youpayclienttransactiondata',
            name='available_points',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Available points for the card', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='youpayclienttransactiondata',
            name='is_full_redemption',
            field=models.BooleanField(blank=True, db_index=True, help_text='Denotes whether the redemption is full or not.', null=True),
        ),
        migrations.AddField(
            model_name='youpayclienttransactiondata',
            name='payable_amount',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='amount which is paid using credit/debit card by the customer', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='youpayclienttransactiondata',
            name='redeemed_amount',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='amount which was redeemed on ADCB', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='youpayclienttransactiondata',
            name='redeemed_points',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='points which was redeemed on ADCB', max_digits=12, null=True),
        ),
    ]
