# Generated by Django 4.0.6 on 2023-02-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youpayclient', '0004_youpayclienttransactiondata_cancel_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youpayclienttransactiondata',
            name='processing_fee',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='used to store gateway processing fee', max_digits=12, null=True),
        ),
    ]
