# Generated by Django 4.0.6 on 2023-03-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youpayclient', '0005_youpayclienttransactiondata_processing_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='youpayclienttransactiondata',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='used to store gateway total amount paid by customer', max_digits=12, null=True),
        ),
    ]
