# Generated by Django 4.0.6 on 2023-03-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youpayclient', '0006_youpayclienttransactiondata_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='youpayclienttransactiondata',
            name='gateway_charge',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Used to store calculated gateway charges based on the configuration', max_digits=12, null=True),
        ),
    ]
