# Generated by Django 4.0.6 on 2023-08-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youpayclient', '0009_alter_youpayclienttransactiondata_base_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youpayclienttransactiondata',
            name='earned_point',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Earned point for the transaction via corresponding payment method', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='youpayclienttransactiondata',
            name='is_qitaf_enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='youpayclienttransactiondata',
            name='qitaf_request_id',
            field=models.CharField(blank=True, db_index=True, help_text='Request id generated by Qitaf', max_length=100, null=True),
        ),
    ]
