# Generated by Django 4.0.6 on 2023-04-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleWalletTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_in', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('amount_out', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('user', models.CharField(max_length=255)),
            ],
        ),
    ]
